# Copyright (c) 2026 Raul I. Lopez
# SPDX-License-Identifier: MIT
# See LICENSE file for details.

CC        = clang
CFLAGS    = -Wall -Wextra -O2
OBJCFLAGS = -Wall -Wextra -O2 -fobjc-arc
VERSION_BASE = 0.5
VERSION_PATCH = $(shell sh -c 'git rev-list --count HEAD 2>/dev/null || echo 0')
GIT_REF = $(shell sh -c 'git rev-parse --short HEAD 2>/dev/null || echo nogit')
DIRTY_SUFFIX = $(shell sh -c 'git diff --quiet --ignore-submodules HEAD -- . 2>/dev/null; rc=$$?; if [ "$$rc" -eq 0 ]; then printf ""; else printf ".dirty"; fi')
APP_VERSION = $(VERSION_BASE).$(VERSION_PATCH)
BUILD_VERSION = $(APP_VERSION)+$(GIT_REF)$(DIRTY_SUFFIX)
BUILD_HDR = build_version.h
FRAMEWORKS = -framework Foundation \
             -framework Vision     \
             -framework AppKit     \
             -framework CoreGraphics \
             -framework CoreText   \
             -framework ImageIO    \
             -framework UniformTypeIdentifiers \
             -framework AVFoundation \
             -framework CoreMedia  \
             -framework CoreVideo

TARGET  = vision
OBJECTS = main.o face_detector.o video_detector.o body_detector.o gait_detector.o

.PHONY: all clean FORCE

all: $(BUILD_HDR) $(TARGET)

FORCE:

$(BUILD_HDR): FORCE
	@printf '%s\n' '/* Auto-generated by Makefile. */' '#ifndef BUILD_VERSION_H' '#define BUILD_VERSION_H' '#define APP_VERSION "$(APP_VERSION)"' '#define BUILD_VERSION "$(BUILD_VERSION)"' '#endif' > $(BUILD_HDR)

$(TARGET): $(OBJECTS)
	$(CC) -o $@ $^ $(FRAMEWORKS)

main.o: main.c face_detector.h gait_detector.h body_detector.h video_detector.h $(BUILD_HDR)
	$(CC) $(CFLAGS) -c main.c

face_detector.o: face_detector.m face_detector.h face_detector_internal.h
	$(CC) $(OBJCFLAGS) -c face_detector.m

video_detector.o: video_detector.m video_detector.h face_detector.h face_detector_internal.h
	$(CC) $(OBJCFLAGS) -c video_detector.m

body_detector.o: body_detector.m body_detector.h face_detector_internal.h
	$(CC) $(OBJCFLAGS) -c body_detector.m

gait_detector.o: gait_detector.m gait_detector.h face_detector_internal.h
	$(CC) $(OBJCFLAGS) -c gait_detector.m

clean:
	rm -f $(OBJECTS) $(TARGET) $(BUILD_HDR)
